/**
 * Create j_hub_optimization_extracts table
 * Stores extracted summaries of optimization actions for Step 3
 */

-- Create table
CREATE TABLE IF NOT EXISTS public.j_hub_optimization_extracts (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  recording_id uuid NOT NULL REFERENCES public.j_hub_optimization_recordings(id) ON DELETE CASCADE,

  -- Extract content
  extract_text text NOT NULL, -- Formatted bullet list generated by AI
  actions jsonb, -- Structured actions array for future features

  -- Versioning
  previous_version text, -- Store previous version for undo
  edit_count integer DEFAULT 0 NOT NULL,

  -- Timestamps
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,

  -- Constraints
  CONSTRAINT unique_recording_extract UNIQUE (recording_id)
);

-- Create indexes
CREATE INDEX idx_optimization_extracts_recording ON public.j_hub_optimization_extracts(recording_id);
CREATE INDEX idx_optimization_extracts_updated ON public.j_hub_optimization_extracts(updated_at DESC);

-- Enable RLS
ALTER TABLE public.j_hub_optimization_extracts ENABLE ROW LEVEL SECURITY;

-- RLS Policies
-- Users can view their own extracts
CREATE POLICY "Users can view their own extracts"
  ON public.j_hub_optimization_extracts
  FOR SELECT
  USING (
    recording_id IN (
      SELECT id FROM public.j_hub_optimization_recordings
      WHERE user_id = auth.uid()
    )
  );

-- Users can insert their own extracts
CREATE POLICY "Users can insert their own extracts"
  ON public.j_hub_optimization_extracts
  FOR INSERT
  WITH CHECK (
    recording_id IN (
      SELECT id FROM public.j_hub_optimization_recordings
      WHERE user_id = auth.uid()
    )
  );

-- Users can update their own extracts
CREATE POLICY "Users can update their own extracts"
  ON public.j_hub_optimization_extracts
  FOR UPDATE
  USING (
    recording_id IN (
      SELECT id FROM public.j_hub_optimization_recordings
      WHERE user_id = auth.uid()
    )
  );

-- Admins can view all extracts
CREATE POLICY "Admins can view all extracts"
  ON public.j_hub_optimization_extracts
  FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM public.j_ads_users
      WHERE id = auth.uid() AND role = 'admin'
    )
  );

-- Admins can update all extracts
CREATE POLICY "Admins can update all extracts"
  ON public.j_hub_optimization_extracts
  FOR UPDATE
  USING (
    EXISTS (
      SELECT 1 FROM public.j_ads_users
      WHERE id = auth.uid() AND role = 'admin'
    )
  );

-- Add comment
COMMENT ON TABLE public.j_hub_optimization_extracts IS 'Stores extracted summaries of optimization actions (Step 3)';
