// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Environment variables are REQUIRED - fail fast if missing
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY ||
  import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Validate required environment variables
if (!SUPABASE_URL) {
  throw new Error(
    '❌ VITE_SUPABASE_URL is not defined. ' +
    'Please set it in .env.local for development or in Vercel for production.'
  );
}

if (!SUPABASE_PUBLISHABLE_KEY) {
  throw new Error(
    '❌ VITE_SUPABASE_ANON_KEY is not defined. ' +
    'Please set it in .env.local for development or in Vercel for production.'
  );
}

// Log which Supabase instance we're using (helps catch accidental production connections)
if (import.meta.env.DEV) {
  const isLocal = SUPABASE_URL.includes('127.0.0.1') || SUPABASE_URL.includes('localhost');
  console.log(`🔗 Supabase: ${isLocal ? 'LOCAL' : 'PRODUCTION'} (${SUPABASE_URL})`);
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);